---
title: "Post Distribution Summary"
output: html_document
---

```{r, echo=FALSE, message=FALSE}
setwd("~/Programming/Projects/R/PDMSummary/")
source("password.R") ## loads a variable called password
library(RCurl)
library(stringr)
upass = str_c("mcnepal:", password)
dataStreamPdm = getURI("http://ona.io/api/v1/data/69069.csv", userpwd=upass, httpauth = 1L)
pdm = read.csv(textConnection(dataStreamPdm), na.strings="n/a")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

library(dplyr)
library(jsonlite)

pdm_sindhupalchowk = filter(pdm, pdm$sec_0.district_lst == "Sindupalchowk")
pdm_nuwakot = filter(pdm, pdm$sec_0.district_lst == "Nawakot")
pdm_kavre = filter(pdm, pdm$sec_0.district_lst == "Kabhre")
pdm_dolakha = filter(pdm, pdm$sec_0.district_lst == "Dolakha")

district_record_count = data.frame( c("Sindhupalchowk","Nuwakot","Kavrepalanchowk", "Dolakha"), c(nrow(pdm_sindhupalchowk),nrow(pdm_nuwakot),nrow(pdm_kavre),nrow(pdm_dolakha)))

```

```{r, echo=FALSE, message=FALSE}
knitr::kable(district_record_count, col.names = c ("District","Number of Records"))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
addColumnSummary <- function(district, vdc ,column, currentSummary, columnNames){
district_summary_column <- as.data.frame.matrix(district %>% group_by_(vdc_col) %>% select_(column)%>% table())
colnames(district_summary_column) <- columnNames
district_summary_column$VDC <- rownames(district_summary_column)
currentSummary <- merge(currentSummary, district_summary_column, by.y = "VDC", by.x = "VDC") 
return (currentSummary)
}


makeSummary <- function(district, vdc_col){

district_summary <- as.data.frame.matrix (district %>% group_by_(vdc_col) %>% select(sec_1.respondent.ethnicity_lst) %>% table())
district_summary$VDC <- rownames(district_summary)
names(district_summary) <- sub("other", "Other", names(district_summary))
names(district_summary) <- sub("Adibasi_Janjati_Newar", "Adibasi Janjati", names(district_summary))

district_summary_HouseHoldMembers <- district %>% group_by_(vdc_col) %>% summarise( maleOne = sum(sec_1.hh_pop.male0_5, na.rm = TRUE), maleTwo = sum(sec_1.hh_pop.male6_11, na.rm = TRUE), maleThree = sum (sec_1.hh_pop.male12_24, na.rm = TRUE), maleFour = sum(sec_1.hh_pop.male25, na.rm = TRUE),femaleFive = sum(sec_1.hh_pop.female0_5, na.rm = TRUE), femaleSix = sum(sec_1.hh_pop.female6_11, na.rm = TRUE), femaleSeven = sum (sec_1.hh_pop.female12_24, na.rm = TRUE), femaleEight= sum(sec_1.hh_pop.female25, na.rm = TRUE), pop = sum(sec_1.hh_pop.total_hh_members, na.rm = TRUE)/n() )
names(district_summary_HouseHoldMembers) <- sub("maleOne", "Total Male Population Aged 0-5", names(district_summary_HouseHoldMembers))
names(district_summary_HouseHoldMembers) <- sub("maleTwo", "Total Male Population Aged 6-11", names(district_summary_HouseHoldMembers))
names(district_summary_HouseHoldMembers) <- sub("maleThree", "Total Male Population Aged 12-24", names(district_summary_HouseHoldMembers))
names(district_summary_HouseHoldMembers) <- sub("maleFour", "Total Male Population Aged Above 25", names(district_summary_HouseHoldMembers))
names(district_summary_HouseHoldMembers) <- sub("femaleFive", "Total Female Population Aged 0-5", names(district_summary_HouseHoldMembers))
names(district_summary_HouseHoldMembers) <- sub("femaleSix", "Total Female Population Aged 6-11", names(district_summary_HouseHoldMembers))
names(district_summary_HouseHoldMembers) <- sub("femaleSeven", "Total Female Population Aged 12-24", names(district_summary_HouseHoldMembers))
names(district_summary_HouseHoldMembers) <- sub("femaleEight", "Total Female Population Aged Above 25", names(district_summary_HouseHoldMembers))
names(district_summary_HouseHoldMembers) <- sub("pop", "Average Members in Household", names(district_summary_HouseHoldMembers))
district_summary <- merge(district_summary, district_summary_HouseHoldMembers, by.y = vdc_col, by.x = "VDC")


district_summary_assistance <- district %>% group_by_(vdc_col) %>% summarise(Ast1 = table(sec_1.assistant_type.nfi)["True"], Ast2 = table(sec_1.assistant_type.cash)["True"], Ast3 = table(sec_1.assistant_type.food)["True"], Ast4 = table(sec_1.assistant_type.med)["True"], Ast5 = table(sec_1.assistant_type.gik)["True"], Ast6 = table(sec_1.assistant_type.tents)["True"], Ast7 = table(sec_1.assistant_type.other)["True"])
names(district_summary_assistance) <- sub("Ast1", "Recived NFI After Earthquake", names(district_summary_assistance))
names(district_summary_assistance) <- sub("Ast2", "Recived Cash After Earthquake", names(district_summary_assistance))
names(district_summary_assistance) <- sub("Ast3", "Recived Food After Earthquake", names(district_summary_assistance))
names(district_summary_assistance) <- sub("Ast4", "Recived Medical Care After Earthquake", names(district_summary_assistance))
names(district_summary_assistance) <- sub("Ast5", "Recived Supplies of Temporary Shelter After Earthquake", names(district_summary_assistance))
names(district_summary_assistance) <- sub("Ast6", "Recived Tents After Earthquake", names(district_summary_assistance))
names(district_summary_assistance) <- sub("Ast7", "Recived Other Assistance After Earthquake", names(district_summary_assistance))
district_summary <- merge(district_summary, district_summary_assistance, by.y = vdc_col, by.x = "VDC")

district_summary_cashrecieved <- district %>% group_by_(vdc_col) %>% summarise(cs1 = table(sec_2.gen_cash_sources.relatives_friends)["True"], cs2 = table(sec_2.gen_cash_sources.government)["True"], cs3 = table(sec_2.gen_cash_sources.private_sector)["True"], cs4 = table(sec_2.gen_cash_sources.ngo)["True"])
names(district_summary_cashrecieved) <- sub("cs1", "Recived Cash From Relative and Friends", names(district_summary_cashrecieved))
names(district_summary_cashrecieved) <- sub("cs2", "Recived Cash From Government", names(district_summary_cashrecieved))
names(district_summary_cashrecieved) <- sub("cs3", "Recived Cash From Private Sector", names(district_summary_cashrecieved))
names(district_summary_cashrecieved) <- sub("cs4", "Recived Cash From NGO's", names(district_summary_cashrecieved))
district_summary <- merge(district_summary, district_summary_cashrecieved, by.y = vdc_col, by.x = "VDC")


district_summary_travletime <- as.data.frame.matrix(district %>% group_by_(vdc_col) %>% select(sec_4.distribution.dist_travel)%>% table())
colnames(district_summary_travletime) <- c("Travelled One Hour or Less","Travelled 1 to 2 Hours", "Travelled 2 to 3 Hours", "Travelled 3 to 4 Hours", "Travelled More Than 4 Hours", "Travel Time Unknown")
district_summary_travletime$VDC <- rownames(district_summary_travletime)
district_summary <- merge(district_summary, district_summary_travletime, by.y = "VDC", by.x = "VDC")

district_summary_travletransport <- as.data.frame.matrix(district %>% group_by_(vdc_col) %>% select(sec_4.distribution.dist_mode)%>% table())
colnames(district_summary_travletransport) <- c("Travelled by Animal","Travelled by Foot", "Travelled by Other Source", "Travelled by Porter ", "Travelled by Truck", "Travel by Motor Vehicle")
district_summary_travletransport$VDC <- rownames(district_summary_travletransport)
district_summary <- merge(district_summary, district_summary_travletransport, by.y = "VDC", by.x = "VDC")


district_summary_disablity <- as.data.frame.matrix(district %>% group_by_(vdc_col) %>% select(sec_1.respondent.hh_categories.physical_disability)%>% table())
colnames(district_summary_disablity) <- c("Household Without Disablity","Household With Disablity")
district_summary_disablity$VDC <- rownames(district_summary_disablity)
district_summary <- merge(district_summary, district_summary_disablity, by.y = "VDC", by.x = "VDC")

district_summary_debt <- as.data.frame.matrix(district %>% group_by_(vdc_col) %>% select(sec_7.debt_quake)%>% table())
colnames(district_summary_debt) <- c("No Debt Due to Earthquake","Debt Taken Due to Earthquake")
district_summary_debt$VDC <- rownames(district_summary_debt)
district_summary <- merge(district_summary, district_summary_debt, by.y = "VDC", by.x = "VDC")

district_summary_solarLampNotRecieved <- as.data.frame.matrix(district %>% group_by_(vdc_col) %>% select(sec_4.receive_lantern)%>% table())
names(district_summary_solarLampNotRecieved) <- sub("1", "Recived Solar Lamp", names(district_summary_solarLampNotRecieved))
names(district_summary_solarLampNotRecieved) <- sub("0", "Did not Recieve Solar Lamp", names(district_summary_solarLampNotRecieved))
district_summary_solarLampNotRecieved$VDC <- rownames(district_summary_solarLampNotRecieved)
district_summary <- merge(district_summary, district_summary_solarLampNotRecieved, by.y = "VDC", by.x = "VDC")


district_summary_solarLamp <- as.data.frame.matrix(district %>% group_by_(vdc_col) %>% select(sec_4.lantern_use)%>% table())
colnames(district_summary_solarLamp) <- c("Solar Lamp Used Daily","Solar Lamp Used 4-5 Times/Week", "Solar Lamp Used 2-3 Times/Week", "Solar Lamp Seldom Used", "Never Used Solar Lamp")
district_summary_solarLamp$VDC <- rownames(district_summary_solarLamp)
district_summary <- merge(district_summary, district_summary_solarLamp, by.y = "VDC", by.x = "VDC")

district_summary_solarSecurity <- as.data.frame.matrix(district %>% group_by_(vdc_col) %>% select(sec_4.solar_light.light_safety)%>% table())
names(district_summary_solarSecurity) <- sub("1", "Solar Lamp Enchance Securty: Strongly Agree", names(district_summary_solarSecurity))
names(district_summary_solarSecurity) <- sub("2", "Solar Lamp Enchance Securty: Agree", names(district_summary_solarSecurity))
names(district_summary_solarSecurity) <- sub("3", "Solar Lamp Enchance Securty: Neutral", names(district_summary_solarSecurity))
names(district_summary_solarSecurity) <- sub("4", "Solar Lamp Enchance Securty: Disagree", names(district_summary_solarSecurity))
names(district_summary_solarSecurity) <- sub("5", "Solar Lamp Enchance Securty: Strongly Disagree", names(district_summary_solarSecurity))
district_summary_solarSecurity$VDC <- rownames(district_summary_solarSecurity)
district_summary <- merge(district_summary, district_summary_solarSecurity, by.y = "VDC", by.x = "VDC")

district_summary_solarStudy <- as.data.frame.matrix(district %>% group_by_(vdc_col) %>% select(sec_4.solar_light.study_light)%>% table())
names(district_summary_solarStudy) <- sub("1", "Solar Lamp Helps Children Study: Strongly Agree", names(district_summary_solarStudy))
names(district_summary_solarStudy) <- sub("2", "Solar Lamp Helps Children Study: Agree", names(district_summary_solarStudy))
names(district_summary_solarStudy) <- sub("3", "Solar Lamp Helps Children Study: Neutral", names(district_summary_solarStudy))
names(district_summary_solarStudy) <- sub("4", "Solar Lamp Helps Children Study: Disagree", names(district_summary_solarStudy))
names(district_summary_solarStudy) <- sub("5", "Solar Lamp Helps Children Study: Strongly Disagree", names(district_summary_solarStudy))
names(district_summary_solarStudy) <- sub("6", "Solar Lamp Helps Children Study: No Children", names(district_summary_solarStudy))
names(district_summary_solarStudy) <- sub("7", "Solar Lamp Helps Children Study: Children Not in School ", names(district_summary_solarStudy))
district_summary_solarStudy$VDC <- rownames(district_summary_solarStudy)
district_summary <- merge(district_summary, district_summary_solarStudy, by.y = "VDC", by.x = "VDC")


district_summary_solarSavings <- as.data.frame.matrix(district %>% group_by_(vdc_col) %>% select(sec_4.solar_light.lighting_savings)%>% table())
names(district_summary_solarSavings) <- sub("1", "Solar Lamp Saves Money: Strongly Agree", names(district_summary_solarSavings))
names(district_summary_solarSavings) <- sub("2", "Solar Lamp Saves Money: Agree", names(district_summary_solarSavings))
names(district_summary_solarSavings) <- sub("3", "Solar Lamp Saves Money: Neutral", names(district_summary_solarSavings))
names(district_summary_solarSavings) <- sub("4", "Solar Lamp Saves Money: Disagree", names(district_summary_solarSavings))
names(district_summary_solarSavings) <- sub("5", "Solar Lamp Saves money: Strongly Disagree", names(district_summary_solarSavings))
district_summary_solarSavings$VDC <- rownames(district_summary_solarSavings)
district_summary <- merge(district_summary, district_summary_solarSavings, by.y = "VDC", by.x = "VDC")

district_summary_urgentItemsNotPresent <- as.data.frame.matrix(district %>% group_by_(vdc_col) %>% select(sec_4.urgently_needed)%>% table())
names(district_summary_urgentItemsNotPresent) <- sub("1", "Nedded Additional Urgent Items not Present in the Kit", names(district_summary_urgentItemsNotPresent))
names(district_summary_urgentItemsNotPresent) <- sub("0", "Did not Require Additional Urgent Items", names(district_summary_urgentItemsNotPresent))
district_summary_urgentItemsNotPresent$VDC <- rownames(district_summary_urgentItemsNotPresent)
district_summary <- merge(district_summary, district_summary_urgentItemsNotPresent, by.y = "VDC", by.x = "VDC")


district_summary_itemsRequired <- district %>% group_by_(vdc_col) %>% summarise(Needs1 = table(sec_4.needs.1)["True"], Needs2 = table(sec_4.needs.2)["True"], Needs3 = table(sec_4.needs.3)["True"], Needs4 = table(sec_4.needs.4)["True"], Needs5 = table(sec_4.needs.5)["True"], Needs6 = table(sec_4.needs.6)["True"], Needs7 = table(sec_4.needs.7)["True"], Needs8 = table(sec_4.needs.8)["True"], Needs9 = table(sec_4.needs.9)["True"])
names(district_summary_itemsRequired) <- sub("Needs1", "Needed: Shelter Construction Materials", names(district_summary_itemsRequired))
names(district_summary_itemsRequired) <- sub("Needs2", "Nedded: Food", names(district_summary_itemsRequired))
names(district_summary_itemsRequired) <- sub("Needs3", "Nedded: Clothing", names(district_summary_itemsRequired))
names(district_summary_itemsRequired) <- sub("Needs4", "Nedded: Medical Supplies", names(district_summary_itemsRequired))
names(district_summary_itemsRequired) <- sub("Needs5", "Nedded: Agricultural Inputs", names(district_summary_itemsRequired))
names(district_summary_itemsRequired) <- sub("Needs6", "Nedded: Basic Household Items", names(district_summary_itemsRequired))
names(district_summary_itemsRequired) <- sub("Needs7", "Nedded: Large Household Items", names(district_summary_itemsRequired))
names(district_summary_itemsRequired) <- sub("Needs8", "Nedded: Hygine Products", names(district_summary_itemsRequired))
names(district_summary_itemsRequired) <- sub("Needs9", "Nedded: Educational Materials", names(district_summary_itemsRequired))
district_summary <- merge(district_summary, district_summary_itemsRequired, by.y = vdc_col, by.x = "VDC")



district_summary_debtSpending <- district %>% group_by_(vdc_col) %>% summarise(FoodSpending = sum(sec_7.debt_earthquake.debt_food, na.rm = TRUE), HouseholdItemSpending = sum(sec_7.debt_earthquake.debt_basic_hh, na.rm = TRUE), ConstructionSpending = (sum (sec_7.debt_earthquake.debt_shelter, na.rm = TRUE) + sum(sec_7.debt_earthquake.debt_labor, na.rm = TRUE)), SavingAfterDebtSpending = sum(sec_7.debt_earthquake.debt_savings, na.rm = TRUE))
district_summary <- merge(district_summary, district_summary_debtSpending, by.y = vdc_col, by.x = "VDC")

district_summary_female <- as.data.frame.matrix(district %>% group_by_(vdc_col) %>% select(sec_1.respondent.respondent_female)%>% table())
colnames(district_summary_female) <- c("Respondent Male","Respondent Female")
district_summary_female$VDC <- rownames(district_summary_female)
district_summary <- merge(district_summary, district_summary_female, by.y = "VDC", by.x = "VDC")

district_summary_elderly <- as.data.frame.matrix (district %>% group_by_(vdc_col) %>% select(sec_1.respondent.hh_categories.elderly_people) %>% table())
colnames(district_summary_elderly) <- c("No Elderly","Has Elderly")
district_summary_elderly$VDC <- rownames(district_summary_elderly)
district_summary <- merge(district_summary, district_summary_elderly, by.y = "VDC", by.x = "VDC")


district_summary_pregnant <- as.data.frame.matrix (district %>% group_by_(vdc_col) %>% select(sec_1.respondent.hh_categories.pregnant_lactating_women) %>% table())
colnames(district_summary_pregnant)<- c("No Preagnant Women","Has Pregnant Women")
district_summary_pregnant$VDC <- rownames(district_summary_pregnant)
district_summary <- merge(district_summary, district_summary_pregnant, by.y = "VDC", by.x = "VDC")


district_vdc_count <- district %>% group_by_(vdc_col) %>% summarise(TotalRecords = n()) 
district_summary <- merge(district_summary, district_vdc_count, by.y = vdc_col, by.x = "VDC")

district_summary <- t(district_summary)
colnames(district_summary) <- district_summary[1,]
district_summary <- as.data.frame(district_summary [-1,])
# district_summary$DistrictTotal <- rowSums(sapply(district_summary, as.numeric))
return(district_summary)
}

dolakha_summary <- makeSummary(pdm_dolakha, "sec_0.vdc_dolakha")
write(toJSON(dolakha_summary, preety = T),file = "JSONDump/dolakha_summary.json")
kavre_summary <- makeSummary(pdm_kavre, "sec_0.vdc_kabhre")
write(toJSON(kavre_summary, preety = T),file = "JSONDump/kavre_summary.json")
nuwakot_summary <- makeSummary(pdm_nuwakot, "sec_0.vdc_nawakot")
write(toJSON(nuwakot_summary, preety = T),file = "JSONDump/nuwakot_summary.json")
sindhupalchowk_summary <- makeSummary(pdm_sindhupalchowk, "sec_0.vdc_sindu")
write(toJSON(sindhupalchowk_summary, preety = T),file = "JSONDump/sindhupalchowk_summary.json")
district_level_summary <- makeSummary(pdm, "sec_0.district_lst")
write(toJSON(district_level_summary, preety = T),file = "JSONDump/district_level_summary.json")
```

##District Level Summary
```{r, echo=FALSE, message=FALSE}
knitr::kable(district_level_summary)
```

##Dolakha Summary 
```{r, echo=FALSE, message=FALSE}
knitr::kable(dolakha_summary)
```

##Kavre Summary 
```{r, echo=FALSE, message=FALSE}
knitr::kable(kavre_summary)
```

##Nuwakot Summary 
```{r, echo=FALSE, message=FALSE}
knitr::kable(nuwakot_summary)
```

##Sindhupalchowk Summary 
```{r, echo=FALSE, message=FALSE}
knitr::kable(sindhupalchowk_summary)
```

Report Generated on `r date()` from `r nrow(pdm)` records. 